name: Unitest

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
        packages: redis==4.3.5
    - name: Python Unit Test
      run: python -m unittest test/test_unit.py
    - name: Python Validtion Test
      run: python -m unittest test/test_validation.py
